controller_list:
  - name: wpb_mani_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: wpb_mani_gripper_controller
    action_ns: gripper_command
    type: GripperCommand
    default: true
    joints:
      - gripper
      - gripper_sub